name: Build Containers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        starenv: [root5, root616]
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebuild up to base-stage
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/star-sw-${{ matrix.starenv }}-base:cache
          cache-to:   type=registry,ref=ghcr.io/${{ github.repository_owner }}/star-sw-${{ matrix.starenv }}-base:cache,mode=max
          build-args: starenv=${{ matrix.starenv }}
          target: base-stage
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/star-sw-${{ matrix.starenv }}-base:${{ steps.branch-name.outputs.current_branch }}_latest

      - name: Build release container
        if: steps.branch-name.outputs.is_tag == 'true'
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/star-sw-${{ matrix.starenv }}-base:cache
          build-args: starenv=${{ matrix.starenv }}
          target: build-stage
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/star-sw-${{ matrix.starenv }}-build:${{ steps.branch-name.outputs.tag }}
